import { ChainName, MapChainIdName } from "../types";

export const mapChainIdName: MapChainIdName = {
  1: ChainName.ETHEREUM,
  3: ChainName.ETHEREUM,
  56: ChainName.BINANCE,
  97: ChainName.BINANCE,
  250: ChainName.FANTOM,
  4002: ChainName.FANTOM,
  1313161554: ChainName.AURORA,
  1313161555: ChainName.AURORA,
  43113: ChainName.AVALANCHE,
  43114: ChainName.AVALANCHE,
  1287: ChainName.MOONBEAM,
  1284: ChainName.MOONBEAM,
  137: ChainName.POLYGON,
  80001: ChainName.POLYGON,
  cosmoshub: ChainName.COSMOS,
  "osmo-test-4": ChainName.OSMOSIS4,
  "osmosis-4": ChainName.OSMOSIS,
  "sei-testnet-1": ChainName.SEI,
  "fetchhub-3": ChainName.FETCH,
  "crescent-1": ChainName.CRESCENT,
  "emoney-3": ChainName.EMONEY,
  "injective-1": ChainName.INJECTIVE,
  "juno-1": ChainName.JUNO,
  "kaiyo-1": ChainName.KUJIRA,
  "harpoon-4": ChainName.KUJIRA,
  "secret-4": ChainName.SECRET,
  "terra-2": ChainName.TERRA2,
  "phoenix-1": ChainName.TERRA2,
  "axelar-testnet-lisbon-3": ChainName.AXELARNET,
  "cosmoshub-4": ChainName.COSMOS
};
